<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[NewWork]]>
    </line>
    <line>
      <![CDATA[NewWork]]>
    </line>
  </reporter-output>
  <suite started-at="2023-03-29T13:11:31 IST" name="Suite" finished-at="2023-03-29T13:12:45 IST" duration-ms="73786">
    <groups>
    </groups>
    <test started-at="2023-03-29T13:11:31 IST" name="Test" finished-at="2023-03-29T13:12:45 IST" duration-ms="73786">
      <class name="test.com.test.testclass">
        <test-method is-config="true" signature="config()[pri:0, instance:test.com.test.testclass@7f3b84b8]" started-at="2023-03-29T13:11:31 IST" name="config" finished-at="2023-03-29T13:11:31 IST" duration-ms="28" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- config -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.com.test.testclass@7f3b84b8]" started-at="2023-03-29T13:11:31 IST" name="setup" finished-at="2023-03-29T13:11:49 IST" duration-ms="17964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="resetpass()[pri:0, instance:test.com.test.testclass@7f3b84b8]" started-at="2023-03-29T13:11:49 IST" name="resetpass" finished-at="2023-03-29T13:12:05 IST" duration-ms="16001" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/login] but found [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/lgin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/login] but found [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/lgin]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.com.test.testclass.resetpass(testclass.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[NewWork]]>
            </line>
          </reporter-output>
        </test-method> <!-- resetpass -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.com.test.testclass@7f3b84b8]" started-at="2023-03-29T13:12:14 IST" name="setup" finished-at="2023-03-29T13:12:43 IST" duration-ms="28975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="title()[pri:0, instance:test.com.test.testclass@7f3b84b8]" started-at="2023-03-29T13:12:43 IST" name="title" finished-at="2023-03-29T13:12:45 IST" duration-ms="1925" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[NewWork]]>
            </line>
          </reporter-output>
        </test-method> <!-- title -->
      </class> <!-- test.com.test.testclass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
